services:
  backend:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    # Volúmenes (opcional):
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
